config/routes.rb
Rails.application.routes.draw do
  get 'pages/home' => 'pages#home'
  get 'pages/about' => 'pages#about'
  get 'pages/contact' => 'pages#contact'
  get 'pages/meetup' => 'pages#meetup'
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def meetup
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjOne</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Me</h1>
<p>I was born in a small town in Ontario, Canada but moved around the country many times before being raised in Cape Breton, Nova Scotia.</p>
<p>My Father is a Tradesman, My Mother is a Nurse, I have two sisters, one an RN and the other a psychology major.</p>
<p>For most of my adult life Ive worked as a pipefitter, and am currently a 3<sup>rd</sup> year apprentice.</p>
<p>In december 2017, I saw a page of computer code and was fascinated by this enigma. And since then I've been on a quest to understand it, and have since found a passion in software development.</p>
<%= link_to 'Home' , pages_home_path %>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Josh MacSween</h1>
<h4>Aspiring Rails Developer</h4>

<%= link_to "About" , pages_about_path %>

app/views/pages/meetup.html.erb
<h1>Pages#meetup</h1>
<p>Find me in app/views/pages/meetup.html.erb</p>

app/views/welcome/index.html.erb
<h1>Whaddaya Fuckin' Know</h1>